export const BASE_URL = "http://localhost:3000"

export const REGISTER_URL = "/api/auth/register"
export const LOGIN_URL = "/api/auth/login"
export const GET_ME_URL = "/api/users/me"
export const RECIPE_URL = "/api/recipes"
export const RECIPE_BY_USER_URL = "/api/recipes/user"
export const INGREDIENT_URL = "/api/ingredients"
export const REPORT_URL = "/api/reports"
export const COMMENT_URL = "/api/comments"
